/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package website481;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static boolean searchForMedianOfThreeInt(ArrayList<Integer> array, Integer num1, Integer num2, Integer num3) {
        System.out.println("inside search");
        if (array == null) return false;
  
        for (int elt : array) {
          if (elt == ((num1 + num2 + num3) / 3)) return true;
        }
        return false;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

}
